library(sna)
library(igraph)
links2 <- read.csv("C:/Users/Mahesh/Downloads/SNA-20220407T062620Z-001/SNA/Practical 6/edges1.csv", 
                   header=T, row.names=1)
eq<-equiv.clust(links2)
plot(eq)
g.se<-sedist(links2)
plot(cmdscale(as.dist(g.se)))
b<-blockmodel(links2,eq,h=10)
plot(b)
